require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/foorms", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Foorm. As you add validations to Foorm, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    {
      title: "Birthday form",
      form_items_attributes: [ {
        label: "Name",
        item_type: "text"
      } ]
    }
  }

  let(:invalid_attributes) {
    { title: "" }
  }

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Foorm" do
        expect {
          post foorms_url, params: { foorm: valid_attributes }
        }.to change(Foorm, :count).by(1)
      end

      context "nested attributes" do
        let(:valid_attributes) {
          {
            title: "Birthday form",
            form_items_attributes: [ {
              label: "Name",
              item_type: "text"
            } ]
          }
        }

        it "adds the Form Item" do
          expect {
            post foorms_url, params: { foorm: valid_attributes }
          }.to change(FormItem, :count).by(1)
        end

        it "sets the correct attributes" do
          post foorms_url, params: { foorm: valid_attributes }
          form_item = FormItem.last
          expect(form_item.label).to eq "Name"
          expect(form_item.item_type).to eq "text"
        end

        context "FormInputOption nested attributes" do
            let(:valid_attributes) {
              {
                title: "Birthday form",
                form_items_attributes: [ {
                  label: "Name",
                  item_type: "dropdown",
                  form_item_options_attributes: [
                    {
                      label: "New Label",
                      value: "New Value"
                    },
                    {
                      label: "New Label 2",
                      value: "New Value 2"
                    }
                  ]
                } ]
              }
            }

            it "adds the Form Item" do
              expect {
                post foorms_url, params: { foorm: valid_attributes }
              }.to change(FormItemOption, :count).by(2)
            end

            it "sets the correct attributes" do
              post foorms_url, params: { foorm: valid_attributes }

              form_item_option = FormItemOption.first
              expect(form_item_option.label).to eq "New Label"
              expect(form_item_option.value).to eq "New Value"

              form_item_option = FormItemOption.last
              expect(form_item_option.label).to eq "New Label 2"
              expect(form_item_option.value).to eq "New Value 2"
            end
          end
      end

      it "redirects to the created foorm" do
        post foorms_url, params: { foorm: valid_attributes }
        expect(response).to redirect_to(edit_foorm_url(Foorm.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Foorm" do
        expect {
          post foorms_url, params: { foorm: invalid_attributes }
        }.to change(Foorm, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post foorms_url, params: { foorm: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let!(:foorm) { create(:foorm) }
      let(:new_attributes) do
        { title: "Updated title" }
      end

      before do
        patch foorm_url(foorm), params: { foorm: new_attributes }
        foorm.reload
      end

      it "updates the requested foorm" do
        expect(foorm.title).to eq "Updated title"
      end

      it "redirects to the foorm" do
        expect(response).to redirect_to(edit_foorm_url(foorm))
      end

      context "Updating FormItem" do
        let!(:form_item) { create(:form_item, item_type: "text", foorm: foorm) }
        let(:new_attributes) do
          {
            title: "Updated label",
            form_items_attributes: [ {
              id: form_item.id,
              label: "Updated Label"
            } ]
          }
        end

        it "updates the requested foorm" do
          expect(form_item.reload.label).to eq "Updated Label"
        end

        context "deleting FormItem" do
          let(:new_attributes) do
            {
              title: "Updated label",
              form_items_attributes: [ {
                id: form_item.id,
                label: "Updated Label",
                _destroy: 1
              } ]
            }
          end

          it "removes the FormItem" do
            expect(FormItem.where(id: form_item.id)).to be_empty
          end

          context "with FormItemOptions" do
            let!(:form_item_option) { create(:form_item_option, form_item_id: form_item.id) }
            let(:new_attributes) do
              {
                title: "Updated label",
                form_items_attributes: [ {
                  id: form_item.id,
                  label: "Updated Label",
                  form_item_options_attributes: [ {
                    id: form_item_option.id,
                    label: "New Label",
                    value: "New Value"
                  } ]
                } ]
              }
            end

            it "updates the form item option" do
              form_item_option.reload
              expect(form_item_option.label).to eq "New Label"
              expect(form_item_option.value).to eq "New Value"
            end

            context "deleting FormItemOption" do
              let(:new_attributes) do
                {
                  title: "Updated label",
                  form_items_attributes: [ {
                    id: form_item.id,
                    label: "Updated Label",
                    form_item_options_attributes: [ {
                      id: form_item_option.id,
                      label: "New Label",
                      value: "New Value",
                      _destroy: 1
                    } ]
                  } ]
                }
              end

              it "removes the FormItemOption" do
                expect(FormItemOption.where(id: form_item_option.id)).to be_empty
              end
            end
          end
        end
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        foorm = Foorm.create! valid_attributes
        patch foorm_url(foorm), params: { foorm: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested foorm" do
      foorm = Foorm.create! valid_attributes
      expect {
        delete foorm_url(foorm)
      }.to change(Foorm, :count).by(-1)
    end

    it "redirects to the foorms list" do
      foorm = Foorm.create! valid_attributes
      delete foorm_url(foorm)
      expect(response).to redirect_to(foorms_url)
    end
  end
end
